### PR TITLE
TypeScript Definitions

### PR DESCRIPTION
**Pull request by Aliyss**
It's still a WIP.

Just hoped you could look over it shortly and confirm that my interpretation of the class PoissonDiskSampling is correct.
In which case I would continue. It works for the example afaik. But I'm not sure if implementation which is FixedDensityPDS could also be VariableDensityPDS.

Sample code:
```ts
import PoissonDiskSampling from 'poisson-disk-sampling';

const p = new PoissonDiskSampling({
    shape: [600, 300, 200],
    minDistance: 20,
    maxDistance: 30,
    tries: 10
});
const points = p.fill();

console.log(points);
```

### CODE REVIEW

**Comment by Aliyss** [comment]
Also... should I do the same for [fast-2d-poisson-disk-sampling](https://github.com/kchapelier/fast-2d-poisson-disk-sampling)?
Or is it pretty much the same?

**Comment by kchapelier** [comment]
Hi, thanks for your work on this.

I would recommend pushing the TS types to [DefinitelyTyped](https://definitelytyped.org/), this is also _low-key_ recommended by the [Typescript doc](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) for manually created declaration files. In my opinion this is generally the best way to proceed as this leaves the declaration files in the hands of the people with the know-how (the TS community) without adding maintenance burden on packages' authors.

As for the correctness of the declaration, here are some potential mistakes I noticed, but bear in mind I don't have much experience with TS declaration files:

 * all the `any` could be replaced by `number`, except for tinyNDArray
 * the `rng` arguments of the `VariableDensityPDS` constructor is not mandatory
 * some declarations seem to be duplicated in `FixedDensityPDS`
 * is it necessary / useful to document the methods and properties which are not part of the public API (as defined in the readme) ?

> Also... should I do the same for fast-2d-poisson-disk-sampling?
> Or is it pretty much the same?

The public API of `FastPoissonDiskSampling` is the same as `FixedDensityPDS`'s except for the following:

 * the options of the constructor are slightly different
 * there is no `getAllPointsWithDistance` method
 * the points are always represented as arrays of two numbers.

**Comment by Aliyss** [comment]
Perfect. Thanks for the suggestion and clarifications.

**Comment by Aliyss** [comment]
TS stuff has been added. -> https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53935

**Comment by kchapelier** [comment]
> TS stuff has been added. -> [DefinitelyTyped/DefinitelyTyped#53935](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53935)

Thank you! I've added a [short section](https://github.com/kchapelier/poisson-disk-sampling#typescript-definitions) in the readme explaining how to install the TS definitions files and crediting you.

**Pull request closed without merging**
