### PR TITLE
Rebase of the customDistanceFunction branch

### PR DESCRIPTION
**Pull request by marcofugaro**
Hi! I need to use this library with the custom distance function as described in the issue #1, so sad the implementation was never finished!

For now I did a rebase of this branch on master, so I can use it from github, but would be awesome to see this feature merged and published!

I am willing to help contribute if you're still maintaining this repo

### CODE REVIEW

**Comment by kchapelier** [comment]
Hi @marcofugaro , it is possible to install specific branches from Github using npm (see [doc](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)). You can try the following command to include the customDistanceFunction branch in your project : 
`npm install git://github.com/kchapelier/poisson-disk-sampling.git#customDistanceFunction`

Yarn supposedly also allows this according to https://stackoverflow.com/a/49992734

I'm taking your input at heart and still intent to implement the feature following the design goals described in the related issue (https://github.com/kchapelier/poisson-disk-sampling/issues/1), but I personally have not yet required this specific feature for any project so other imperatives forced me to put this on the back burner several times.

**Comment by kchapelier** [comment]
FYI, this feature has finally been (correctly) implemented in the 2.0.0 version now available on NPM.

**Comment by marcofugaro** [comment]
Nice! The portrait example looks awesome! Is there an example of the `distanceFunction` using an image?

image

**Comment by kchapelier** [comment]
@marcofugaro It really depends on the context of your use of the library. The portrait above was made using node.js with the module "pngjs-nozlib". Here is what it looks like, most of the code is actually:

```js
"use strict";

var Poisson = require('poisson-disk-sampling');
var PNG = require('pngjs-nozlib').PNG;

function outputPng (sampling, drawFunc) {
    var png = new PNG({
        width: sampling.shape[0],
        height: sampling.shape[1],
        colortype: 6,
        inputHasAlpha: true,
        filterType: 4
    });

    var pngData = new Uint8Array(png.data);

    // make it all white
    for (var i = 0; i < pngData.length; i+=1) {
        pngData[i] = 255;
    }

    drawFunc(sampling, pngData);

    png.data = pngData;

    png.pack().pipe(process.stdout);
}

// assume Beethoven.png is a 500x500 image
var data = require('fs').readFileSync('Beethoven.png');
var png = PNG.sync.read(data);

var sampling = new Poisson({
    shape: [500, 500],
    minDistance: 1,
    maxDistance: 30,
    tries: 30,
    distanceFunction: function (p) {
        // retrieve the 0-255 red pixel value remap it 0-1 and apply Math.pow for flavor
        return Math.pow(png.data[(Math.round(p[0]) + Math.round(p[1]) * 500) * 4] / 255, 2.7);
    }
});

sampling.fill();

outputPng(sampling, function (sampling, pngData) {
    sampling.getAllPoints().forEach(function (point) {
        var pixelIndex = (Math.round(point[0]) + Math.round(point[1]) * sampling.shape[0]) * 4;
        var intensity = 0;
        pngData[pixelIndex] = pngData[pixelIndex + 1] = pngData[pixelIndex + 2] = intensity;
    });
});
```

On the browser, you'd have to draw the image on a 2d context canvas and then read its pixel values using `getImageData ` (ref. https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas). I intend to publish an example of that at a later date, but let me know if you encounter an issue.

**Comment by kchapelier** [comment]
@marcofugaro FYI, I added a web example with an image : [example online](http://www.kchapelier.com/poisson-disk-sampling/examples/distance-function-with-images-in-browser/) | [source code](https://github.com/kchapelier/poisson-disk-sampling/tree/master/examples/distance-function-with-images-in-browser/).

**Pull request closed without merging**
