### PR TITLE
Browser build

### PR DESCRIPTION
**Pull request by nullpilot**
See #6 

[Demo](https://codepen.io/jet/pen/ExaROQg)

### CODE REVIEW

**Comment by redblobgames** [comment]
Cool. I've been using https://unpkg.com/poisson-disk@1/src/poisson-disk.min.js but haven't looked closely at how unpkg does it.

**Comment by redblobgames** [comment]
Cool. I had tried https://unpkg.com/poisson-disk-sampling@1 but it didn't work.

**Comment by nullpilot** [comment]
The normal one doesn't work because of the `require()` calls, which is the problem I ran into when trying to use it. Is the minified script an unpkg feature, or is it part of the published package?

**Comment by kchapelier** [comment]
@nullpilot Thanks for your input, having a browser build directly in the repo would indeed be useful. However I'd rather have a browserify-based build process as I'm more confortable with this tool and it is much leaner. I'll tend to it later this week. Sorry for the time you spent on this, I consider it my failing for not providing contribution guidelines...

@redblobgames unpkg expects a browser build to be available in the npm package. This would force node user to download the browser build along with the module everytime they install the module. From what I see, jsdelivr can serve files directly from the github repository which makes more sense from my point of view. There is also wzrd.in which is able to properly compile npm modules and serve them as bundles for the browser ( https://wzrd.in/standalone/poisson-disk-sampling@latest ) but from my experience this service tends to go offline every now and then.

**Pull request closed without merging**
